In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = pd.read_csv('/content/master_data_bbl_.csv')

In [ ]:
data.head(20)

,match_id,season,start_date,venue,innings,ball,batting_team,bowling_team,striker,non_striker,...,extras,wides,noballs,byes,legbyes,penalty,wicket_type,player_dismissed,other_wicket_type,other_player_dismissed
0,BBL1,2023/24,12-07-2023,"Brisbane Cricket Ground, Woolloongabba, Brisbane",1,0.1,Brisbane Heat,Melbourne Stars,UT Khawaja,C Munro,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,BBL1,2023/24,12-07-2023,"Brisbane Cricket Ground, Woolloongabba, Brisbane",1,0.2,Brisbane Heat,Melbourne Stars,UT Khawaja,C Munro,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,BBL1,2023/24,12-07-2023,"Brisbane Cricket Ground, Woolloongabba, Brisbane",1,0.3,Brisbane Heat,Melbourne Stars,UT Khawaja,C Munro,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,BBL1,2023/24,12-07-2023,"Brisbane Cricket Ground, Woolloongabba, Brisbane",1,0.4,Brisbane Heat,Melbourne Stars,UT Khawaja,C Munro,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,BBL1,2023/24,12-07-2023,"Brisbane Cricket Ground, Woolloongabba, Brisbane",1,0.5,Brisbane Heat,Melbourne Stars,C Munro,UT Khawaja,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,BBL1,2023/24,12-07-2023,"Brisbane Cricket Ground, Woolloongabba, Brisbane",1,0.6,Brisbane Heat,Melbourne Stars,C Munro,UT Khawaja,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,BBL1,2023/24,12-07-2023,"Brisbane Cricket Ground, Woolloongabba, Brisbane",1,1.1,Brisbane Heat,Melbourne Stars,UT Khawaja,C Munro,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,BBL1,2023/24,12-07-2023,"Brisbane Cricket Ground, Woolloongabba, Brisbane",1,1.2,Brisbane Heat,Melbourne Stars,UT Khawaja,C Munro,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,BBL1,2023/24,12-07-2023,"Brisbane Cricket Ground, Woolloongabba, Brisbane",1,1.3,Brisbane Heat,Melbourne Stars,UT Khawaja,C Munro,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,BBL1,2023/24,12-07-2023,"Brisbane Cricket Ground, Woolloongabba, Brisbane",1,1.4,Brisbane Heat,Melbourne Stars,C Munro,UT Khawaja,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,BBL1,2023/24,12-07-2023,"Brisbane Cricket Ground, Woolloongabba, Brisbane",1,1.5,Brisbane Heat,Melbourne Stars,C Munro,UT Khawaja,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,BBL1,2023/24,12-07-2023,"Brisbane Cricket Ground, Woolloongabba, Brisbane",1,1.6,Brisbane Heat,Melbourne Stars,C Munro,UT Khawaja,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,BBL1,2023/24,12-07-2023,"Brisbane Cricket Ground, Woolloongabba, Brisbane",1,2.1,Brisbane Heat,Melbourne Stars,UT Khawaja,C Munro,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,BBL1,2023/24,12-07-2023,"Brisbane Cricket Ground, Woolloongabba, Brisbane",1,2.2,Brisbane Heat,Melbourne Stars,UT Khawaja,C Munro,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,BBL1,2023/24,12-07-2023,"Brisbane Cricket Ground, Woolloongabba, Brisbane",1,2.3,Brisbane Heat,Melbourne Stars,UT Khawaja,C Munro,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,BBL1,2023/24,12-07-2023,"Brisbane Cricket Ground, Woolloongabba, Brisbane",1,2.4,Brisbane Heat,Melbourne Stars,C Munro,UT Khawaja,...,1,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
16,BBL1,2023/24,12-07-2023,"Brisbane Cricket Ground, Woolloongabba, Brisbane",1,2.5,Brisbane Heat,Melbourne Stars,UT Khawaja,C Munro,...,1,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
17,BBL1,2023/24,12-07-2023,"Brisbane Cricket Ground, Woolloongabba, Brisbane",1,2.6,Brisbane Heat,Melbourne Stars,C Munro,UT Khawaja,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,BBL1,2023/24,12-07-2023,"Brisbane Cricket Ground, Woolloongabba, Brisbane",1,3.1,Brisbane Heat,Melbourne Stars,C Munro,UT Khawaja,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,BBL1,2023/24,12-07-2023,"Brisbane Cricket Ground, Woolloongabba, Brisbane",1,3.2,Brisbane Heat,Melbourne Stars,C Munro,UT Khawaja,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
data.columns

Index(['match_id', 'season', 'start_date', 'venue', 'innings', 'ball',
       'batting_team', 'bowling_team', 'striker', 'non_striker', 'bowler',
       'runs_off_bat', 'extras', 'wides', 'noballs', 'byes', 'legbyes',
       'penalty', 'wicket_type', 'player_dismissed', 'other_wicket_type',
       'other_player_dismissed'],
      dtype='object')

In [ ]:
batting_team_df = data.groupby('batting_team')['runs_off_bat'].sum().reset_index()
batting_team_df

          batting_team  runs_off_bat
0    Adelaide Strikers          1791
1        Brisbane Heat          1655
2    Hobart Hurricanes          1513
3  Melbourne Renegades          1168
4      Melbourne Stars          1330
5      Perth Scorchers          1492
6        Sydney Sixers          1510
7       Sydney Thunder          1318

In [ ]:
ball_df= data.groupby('batting_team')['ball'].count().reset_index()

In [ ]:
ball_df

          batting_team  ball
0    Adelaide Strikers  1271
1        Brisbane Heat  1299
2    Hobart Hurricanes  1195
3  Melbourne Renegades   929
4      Melbourne Stars  1055
5      Perth Scorchers  1207
6        Sydney Sixers  1229
7       Sydney Thunder  1092

In [ ]:
batting_team_df = pd.merge(batting_team_df,ball_df,on='batting_team',how='inner')

In [ ]:
batting_team_df

          batting_team  runs_off_bat  ball
0    Adelaide Strikers          1791  1271
1        Brisbane Heat          1655  1299
2    Hobart Hurricanes          1513  1195
3  Melbourne Renegades          1168   929
4      Melbourne Stars          1330  1055
5      Perth Scorchers          1492  1207
6        Sydney Sixers          1510  1229
7       Sydney Thunder          1318  1092

In [ ]:
dots_ball = data.groupby('batting_team')['runs_off_bat'].apply(lambda x:(x==0).sum()).reset_index()

In [ ]:
dots_ball.rename(columns={'runs_off_bat':'dots'},inplace=True)

In [ ]:
batting_team_df = pd.merge(batting_team_df,dots_ball,on='batting_team',how='inner')

In [ ]:
batting_team_df

          batting_team  runs_off_bat  ball  dots
0    Adelaide Strikers          1791  1271   449
1        Brisbane Heat          1655  1299   498
2    Hobart Hurricanes          1513  1195   499
3  Melbourne Renegades          1168   929   388
4      Melbourne Stars          1330  1055   428
5      Perth Scorchers          1492  1207   482
6        Sydney Sixers          1510  1229   459
7       Sydney Thunder          1318  1092   413

In [ ]:
fours_count = data.groupby('batting_team')['runs_off_bat'].apply(lambda x:(x == 4).sum()).reset_index()

In [ ]:
fours_count.rename(columns={'runs_off_bat':'4s'},inplace=True)

In [ ]:
batting_team_df = pd.merge(batting_team_df,fours_count,on='batting_team',how='inner')

In [ ]:
batting_team_df

          batting_team  runs_off_bat  ball  dots   4s
0    Adelaide Strikers          1791  1271   449  156
1        Brisbane Heat          1655  1299   498  141
2    Hobart Hurricanes          1513  1195   499  135
3  Melbourne Renegades          1168   929   388   94
4      Melbourne Stars          1330  1055   428  133
5      Perth Scorchers          1492  1207   482  117
6        Sydney Sixers          1510  1229   459  139
7       Sydney Thunder          1318  1092   413  106

In [ ]:
six_count = data.groupby('batting_team')['runs_off_bat'].apply(lambda x:(x == 6).sum()).reset_index()

In [ ]:
six_count.rename(columns = {'runs_off_bat':'6s'},inplace=True)

In [ ]:
batting_team_df = pd.merge(batting_team_df,six_count,on='batting_team',how='inner')

In [ ]:
batting_team_df

          batting_team  runs_off_bat  ball  dots   4s  6s
0    Adelaide Strikers          1791  1271   449  156  77
1        Brisbane Heat          1655  1299   498  141  59
2    Hobart Hurricanes          1513  1195   499  135  64
3  Melbourne Renegades          1168   929   388   94  53
4      Melbourne Stars          1330  1055   428  133  42
5      Perth Scorchers          1492  1207   482  117  61
6        Sydney Sixers          1510  1229   459  139  38
7       Sydney Thunder          1318  1092   413  106  43

In [ ]:
batting_team_df['tot_boundary'] = batting_team_df['4s'] + batting_team_df['6s']

In [ ]:
batting_team_df

          batting_team  runs_off_bat  ball  dots   4s  6s  tot_boundary
0    Adelaide Strikers          1791  1271   449  156  77           233
1        Brisbane Heat          1655  1299   498  141  59           200
2    Hobart Hurricanes          1513  1195   499  135  64           199
3  Melbourne Renegades          1168   929   388   94  53           147
4      Melbourne Stars          1330  1055   428  133  42           175
5      Perth Scorchers          1492  1207   482  117  61           178
6        Sydney Sixers          1510  1229   459  139  38           177
7       Sydney Thunder          1318  1092   413  106  43           149

In [ ]:
wicket_count = data.groupby(['batting_team'])['wicket_type'].count().reset_index()

In [ ]:
wicket_count.head(50)

          batting_team  wicket_type
0    Adelaide Strikers           56
1        Brisbane Heat           76
2    Hobart Hurricanes           67
3  Melbourne Renegades           49
4      Melbourne Stars           60
5      Perth Scorchers           60
6        Sydney Sixers           69
7       Sydney Thunder           74

In [ ]:
batting_team_df = pd.merge(batting_team_df,wicket_count,on='batting_team',how='inner')

In [ ]:
batting_team_df

,batting_team,runs_off_bat,ball,dots,4s,6s,tot_boundary,wicket_type
0,Adelaide Strikers,1791,1271,449,156,77,233,56
1,Brisbane Heat,1655,1299,498,141,59,200,76
2,Hobart Hurricanes,1513,1195,499,135,64,199,67
3,Melbourne Renegades,1168,929,388,94,53,147,49
4,Melbourne Stars,1330,1055,428,133,42,175,60
5,Perth Scorchers,1492,1207,482,117,61,178,60
6,Sydney Sixers,1510,1229,459,139,38,177,69
7,Sydney Thunder,1318,1092,413,106,43,149,74

In [ ]:
all_out_count = data.groupby(['batting_team','match_id'])['wicket_type'].count().reset_index()

In [ ]:
all_out_count.head(50)

           batting_team           match_id  wicket_type
0     Adelaide Strikers              BBL11            6
1     Adelaide Strikers              BBL18            6
2     Adelaide Strikers              BBL20            4
3     Adelaide Strikers              BBL25           10
4     Adelaide Strikers              BBL27            1
5     Adelaide Strikers              BBL31            5
6     Adelaide Strikers              BBL33            2
7     Adelaide Strikers              BBL37            1
8     Adelaide Strikers    BBL42- knockout            7
9     Adelaide Strikers  BBL43- challenger           10
10    Adelaide Strikers               BBL8            4
11        Brisbane Heat               BBL1            3
12        Brisbane Heat              BBL10            4
13        Brisbane Heat              BBL16           10
14        Brisbane Heat              BBL24            4
15        Brisbane Heat              BBL29            7
16        Brisbane Heat              BBL32            6
17        Brisbane Heat              BBL35           10
18        Brisbane Heat   BBL41- qualifier           10
19        Brisbane Heat  BBL43- challenger            7
20        Brisbane Heat       BBL44- final            8
21        Brisbane Heat               BBL6            7
22    Hobart Hurricanes              BBL13            4
23    Hobart Hurricanes              BBL17           10
24    Hobart Hurricanes              BBL21            3
25    Hobart Hurricanes              BBL26            4
26    Hobart Hurricanes              BBL29            9
27    Hobart Hurricanes              BBL31            7
28    Hobart Hurricanes              BBL33            6
29    Hobart Hurricanes              BBL38            8
30    Hobart Hurricanes               BBL5            8
31    Hobart Hurricanes               BBL9            8
32  Melbourne Renegades              BBL10            8
33  Melbourne Renegades              BBL13            5
34  Melbourne Renegades              BBL15            8
35  Melbourne Renegades              BBL18            6
36  Melbourne Renegades               BBL2            7
37  Melbourne Renegades              BBL23            7
38  Melbourne Renegades              BBL26            4
39  Melbourne Renegades              BBL36            4
40      Melbourne Stars               BBL1           10
41      Melbourne Stars              BBL12           10
42      Melbourne Stars              BBL14            6
43      Melbourne Stars              BBL17            3
44      Melbourne Stars              BBL20            3
45      Melbourne Stars              BBL23            2
46      Melbourne Stars              BBL28            4
47      Melbourne Stars              BBL36            8
48      Melbourne Stars              BBL38            4
49      Melbourne Stars               BBL7           10

In [ ]:
import pandas as pd

# Example DataFrame containing all team names
all_teams = data['batting_team'].unique()
result = pd.DataFrame({'batting_team':all_teams})

# Perform a left join with all_teams to include all teams
all =  all_out_count[all_out_count['wicket_type'] == 10].groupby('batting_team').size().reset_index()
all.columns = ['batting_team','10W']
result = result.merge(all,on='batting_team',how='left').fillna(0)

# Replace missing values in '10W' column with 0
result

          batting_team  10W
0        Brisbane Heat  3.0
1      Melbourne Stars  3.0
2        Sydney Sixers  1.0
3  Melbourne Renegades  0.0
4      Perth Scorchers  2.0
5    Hobart Hurricanes  1.0
6       Sydney Thunder  3.0
7    Adelaide Strikers  2.0

In [ ]:
batting_team_df = pd.merge(batting_team_df,result,on='batting_team',how='inner')

In [ ]:
batting_team_df

,batting_team,runs_off_bat,ball,dots,4s,6s,tot_boundary,wicket_type,10W
0,Adelaide Strikers,1791,1271,449,156,77,233,56,2.0
1,Brisbane Heat,1655,1299,498,141,59,200,76,3.0
2,Hobart Hurricanes,1513,1195,499,135,64,199,67,1.0
3,Melbourne Renegades,1168,929,388,94,53,147,49,0.0
4,Melbourne Stars,1330,1055,428,133,42,175,60,3.0
5,Perth Scorchers,1492,1207,482,117,61,178,60,2.0
6,Sydney Sixers,1510,1229,459,139,38,177,69,1.0
7,Sydney Thunder,1318,1092,413,106,43,149,74,3.0

In [ ]:
innings_df = data.groupby('batting_team')['match_id'].nunique().reset_index(name='innings_played')

In [ ]:
innings_df

          batting_team  innings_played
0    Adelaide Strikers              11
1        Brisbane Heat              11
2    Hobart Hurricanes              10
3  Melbourne Renegades               8
4      Melbourne Stars              10
5      Perth Scorchers              11
6        Sydney Sixers              11
7       Sydney Thunder               9

In [ ]:
batting_team_df = pd.merge(batting_team_df,innings_df,on='batting_team',how='inner')

In [ ]:
batting_team_df

,batting_team,runs_off_bat,ball,dots,4s,6s,tot_boundary,wicket_type,10W,innings_played
0,Adelaide Strikers,1791,1271,449,156,77,233,56,2.0,11
1,Brisbane Heat,1655,1299,498,141,59,200,76,3.0,11
2,Hobart Hurricanes,1513,1195,499,135,64,199,67,1.0,10
3,Melbourne Renegades,1168,929,388,94,53,147,49,0.0,8
4,Melbourne Stars,1330,1055,428,133,42,175,60,3.0,10
5,Perth Scorchers,1492,1207,482,117,61,178,60,2.0,11
6,Sydney Sixers,1510,1229,459,139,38,177,69,1.0,11
7,Sydney Thunder,1318,1092,413,106,43,149,74,3.0,9

In [ ]:
batting_team_df['AVG'] = (batting_team_df['runs_off_bat']/batting_team_df['wicket_type']).round(2)

In [ ]:
batting_team_df['SR'] = (batting_team_df['runs_off_bat']/batting_team_df['ball'] *100).round(2)

In [ ]:
batting_team_df

,batting_team,runs_off_bat,ball,dots,4s,6s,tot_boundary,wicket_type,10W,innings_played,AVG,SR
0,Adelaide Strikers,1791,1271,449,156,77,233,56,2.0,11,31.98,140.91
1,Brisbane Heat,1655,1299,498,141,59,200,76,3.0,11,21.78,127.41
2,Hobart Hurricanes,1513,1195,499,135,64,199,67,1.0,10,22.58,126.61
3,Melbourne Renegades,1168,929,388,94,53,147,49,0.0,8,23.84,125.73
4,Melbourne Stars,1330,1055,428,133,42,175,60,3.0,10,22.17,126.07
5,Perth Scorchers,1492,1207,482,117,61,178,60,2.0,11,24.87,123.61
6,Sydney Sixers,1510,1229,459,139,38,177,69,1.0,11,21.88,122.86
7,Sydney Thunder,1318,1092,413,106,43,149,74,3.0,9,17.81,120.70

In [ ]:
HS = data.groupby(['batting_team','match_id'])['runs_off_bat','extras'].sum().reset_index()

<ipython-input-40-dd9e600038a2>:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  HS = data.groupby(['batting_team','match_id'])['runs_off_bat','extras'].sum().reset_index()

In [ ]:
HS.head(20)

         batting_team           match_id  runs_off_bat  extras
0   Adelaide Strikers              BBL11           147       7
1   Adelaide Strikers              BBL18           170       7
2   Adelaide Strikers              BBL20           197       8
3   Adelaide Strikers              BBL25           164       5
4   Adelaide Strikers              BBL27           150       4
5   Adelaide Strikers              BBL31           159       9
6   Adelaide Strikers              BBL33           164       5
7   Adelaide Strikers              BBL37           136       5
8   Adelaide Strikers    BBL42- knockout           151       4
9   Adelaide Strikers  BBL43- challenger           158       2
10  Adelaide Strikers               BBL8           195      10
11      Brisbane Heat               BBL1           190      24
12      Brisbane Heat              BBL10           154       9
13      Brisbane Heat              BBL16           162      10
14      Brisbane Heat              BBL24           101       3
15      Brisbane Heat              BBL29           121      11
16      Brisbane Heat              BBL32           182       9
17      Brisbane Heat              BBL35           120       8
18      Brisbane Heat   BBL41- qualifier           110       3
19      Brisbane Heat  BBL43- challenger           206       8

In [ ]:
max_runs_idx = HS.groupby('batting_team')['runs_off_bat'].idxmax()

# Use the index to retrieve the corresponding values of extras
HS_max = HS.loc[max_runs_idx, ['batting_team', 'runs_off_bat', 'extras']]

HS_max

           batting_team  runs_off_bat  extras
2     Adelaide Strikers           197       8
19        Brisbane Heat           206       8
29    Hobart Hurricanes           178       9
35  Melbourne Renegades           174       4
44      Melbourne Stars           207       4
51      Perth Scorchers           200      11
68        Sydney Sixers           194       7
80       Sydney Thunder           196       4

In [ ]:
batting_team_df = pd.merge(batting_team_df,HS_max,on='batting_team',how='inner')

In [ ]:
batting_team_df['HS'] = batting_team_df['runs_off_bat_y'] + batting_team_df['extras']

In [ ]:
batting_team_df

,batting_team,runs_off_bat_x,ball,dots,4s,6s,tot_boundary,wicket_type,10W,innings_played,AVG,SR,runs_off_bat_y,extras,HS
0,Adelaide Strikers,1791,1271,449,156,77,233,56,2.0,11,31.98,140.91,197,8,205
1,Brisbane Heat,1655,1299,498,141,59,200,76,3.0,11,21.78,127.41,206,8,214
2,Hobart Hurricanes,1513,1195,499,135,64,199,67,1.0,10,22.58,126.61,178,9,187
3,Melbourne Renegades,1168,929,388,94,53,147,49,0.0,8,23.84,125.73,174,4,178
4,Melbourne Stars,1330,1055,428,133,42,175,60,3.0,10,22.17,126.07,207,4,211
5,Perth Scorchers,1492,1207,482,117,61,178,60,2.0,11,24.87,123.61,200,11,211
6,Sydney Sixers,1510,1229,459,139,38,177,69,1.0,11,21.88,122.86,194,7,201
7,Sydney Thunder,1318,1092,413,106,43,149,74,3.0,9,17.81,120.70,196,4,200

In [ ]:
batting_team_df.drop(columns=['runs_off_bat_y','extras'],inplace=True)

In [ ]:
batting_team_df.rename(columns={'batting_team':'TEAMS','runs_off_bat_x':'R','ball':'B','dots':'DOTS','innings_played':'I','tot_boundary':'BOUNDARY','wicket_type':'OUTS'},inplace=True)

In [ ]:
batting_team_df

,TEAMS,R,B,DOTS,4s,6s,BOUNDARY,OUTS,10W,I,AVG,SR,HS
0,Adelaide Strikers,1791,1271,449,156,77,233,56,2.0,11,31.98,140.91,205
1,Brisbane Heat,1655,1299,498,141,59,200,76,3.0,11,21.78,127.41,214
2,Hobart Hurricanes,1513,1195,499,135,64,199,67,1.0,10,22.58,126.61,187
3,Melbourne Renegades,1168,929,388,94,53,147,49,0.0,8,23.84,125.73,178
4,Melbourne Stars,1330,1055,428,133,42,175,60,3.0,10,22.17,126.07,211
5,Perth Scorchers,1492,1207,482,117,61,178,60,2.0,11,24.87,123.61,211
6,Sydney Sixers,1510,1229,459,139,38,177,69,1.0,11,21.88,122.86,201
7,Sydney Thunder,1318,1092,413,106,43,149,74,3.0,9,17.81,120.70,200

In [ ]:
extra_bowled = data.groupby(['batting_team'])['wides','noballs'].sum().reset_index()

<ipython-input-49-a240f8c152f2>:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  extra_bowled = data.groupby(['batting_team'])['wides','noballs'].sum().reset_index()

In [ ]:
extra_bowled

          batting_team  wides  noballs
0    Adelaide Strikers   43.0      1.0
1        Brisbane Heat   49.0      3.0
2    Hobart Hurricanes   44.0      4.0
3  Melbourne Renegades   26.0      4.0
4      Melbourne Stars   38.0      2.0
5      Perth Scorchers   58.0      3.0
6        Sydney Sixers   33.0      4.0
7       Sydney Thunder   29.0      5.0

In [ ]:
batting_team_df.rename(columns={'TEAMS':'batting_team'},inplace=True)

In [ ]:
batting_team_df =batting_team_df.merge(extra_bowled,on='batting_team',how='inner')

In [ ]:
batting_team_df

,batting_team,R,B,DOTS,4s,6s,BOUNDARY,OUTS,10W,I,AVG,SR,HS,wides,noballs
0,Adelaide Strikers,1791,1271,449,156,77,233,56,2.0,11,31.98,140.91,205,43.0,1.0
1,Brisbane Heat,1655,1299,498,141,59,200,76,3.0,11,21.78,127.41,214,49.0,3.0
2,Hobart Hurricanes,1513,1195,499,135,64,199,67,1.0,10,22.58,126.61,187,44.0,4.0
3,Melbourne Renegades,1168,929,388,94,53,147,49,0.0,8,23.84,125.73,178,26.0,4.0
4,Melbourne Stars,1330,1055,428,133,42,175,60,3.0,10,22.17,126.07,211,38.0,2.0
5,Perth Scorchers,1492,1207,482,117,61,178,60,2.0,11,24.87,123.61,211,58.0,3.0
6,Sydney Sixers,1510,1229,459,139,38,177,69,1.0,11,21.88,122.86,201,33.0,4.0
7,Sydney Thunder,1318,1092,413,106,43,149,74,3.0,9,17.81,120.70,200,29.0,5.0

In [ ]:
batting_team_df['CB'] = batting_team_df['B'] - (batting_team_df['wides'] + batting_team_df['noballs'])

In [ ]:
batting_team_df

,batting_team,R,B,DOTS,4s,6s,BOUNDARY,OUTS,10W,I,AVG,SR,HS,wides,noballs,CB
0,Adelaide Strikers,1791,1271,449,156,77,233,56,2.0,11,31.98,140.91,205,43.0,1.0,1227.0
1,Brisbane Heat,1655,1299,498,141,59,200,76,3.0,11,21.78,127.41,214,49.0,3.0,1247.0
2,Hobart Hurricanes,1513,1195,499,135,64,199,67,1.0,10,22.58,126.61,187,44.0,4.0,1147.0
3,Melbourne Renegades,1168,929,388,94,53,147,49,0.0,8,23.84,125.73,178,26.0,4.0,899.0
4,Melbourne Stars,1330,1055,428,133,42,175,60,3.0,10,22.17,126.07,211,38.0,2.0,1015.0
5,Perth Scorchers,1492,1207,482,117,61,178,60,2.0,11,24.87,123.61,211,58.0,3.0,1146.0
6,Sydney Sixers,1510,1229,459,139,38,177,69,1.0,11,21.88,122.86,201,33.0,4.0,1192.0
7,Sydney Thunder,1318,1092,413,106,43,149,74,3.0,9,17.81,120.70,200,29.0,5.0,1058.0

In [ ]:
batting_team_df.drop(columns=['B'],inplace=True)

In [ ]:
batting_team_df.rename(columns={'CB':'B'},inplace=True)

In [ ]:
batting_team_df['4Runs'] = (batting_team_df['4s']*4)

In [ ]:
batting_team_df['6Runs'] = (batting_team_df['6s']*6)

In [ ]:
batting_team_df

,batting_team,R,DOTS,4s,6s,BOUNDARY,OUTS,10W,I,AVG,SR,HS,wides,noballs,B,4Runs,6Runs
0,Adelaide Strikers,1791,449,156,77,233,56,2.0,11,31.98,140.91,205,43.0,1.0,1227.0,624,462
1,Brisbane Heat,1655,498,141,59,200,76,3.0,11,21.78,127.41,214,49.0,3.0,1247.0,564,354
2,Hobart Hurricanes,1513,499,135,64,199,67,1.0,10,22.58,126.61,187,44.0,4.0,1147.0,540,384
3,Melbourne Renegades,1168,388,94,53,147,49,0.0,8,23.84,125.73,178,26.0,4.0,899.0,376,318
4,Melbourne Stars,1330,428,133,42,175,60,3.0,10,22.17,126.07,211,38.0,2.0,1015.0,532,252
5,Perth Scorchers,1492,482,117,61,178,60,2.0,11,24.87,123.61,211,58.0,3.0,1146.0,468,366
6,Sydney Sixers,1510,459,139,38,177,69,1.0,11,21.88,122.86,201,33.0,4.0,1192.0,556,228
7,Sydney Thunder,1318,413,106,43,149,74,3.0,9,17.81,120.70,200,29.0,5.0,1058.0,424,258

In [ ]:
batting_team_df['Boundary %'] = (((batting_team_df['4Runs'] + batting_team_df['6Runs'])/batting_team_df['R'])*100).round(2)

In [ ]:
batting_team_df['Dot%'] = ((batting_team_df['DOTS']/batting_team_df['B'])*100).round(2)

In [ ]:
batting_team_df['BpB'] = (batting_team_df['B']/(batting_team_df['4s']+batting_team_df['6s'])).round(2)

In [ ]:
batting_team_df

,batting_team,R,DOTS,4s,6s,BOUNDARY,OUTS,10W,I,AVG,SR,HS,wides,noballs,B,4Runs,6Runs,Boundary %,Dot%,BpB
0,Adelaide Strikers,1791,449,156,77,233,56,2.0,11,31.98,140.91,205,43.0,1.0,1227.0,624,462,60.64,36.59,5.27
1,Brisbane Heat,1655,498,141,59,200,76,3.0,11,21.78,127.41,214,49.0,3.0,1247.0,564,354,55.47,39.94,6.24
2,Hobart Hurricanes,1513,499,135,64,199,67,1.0,10,22.58,126.61,187,44.0,4.0,1147.0,540,384,61.07,43.50,5.76
3,Melbourne Renegades,1168,388,94,53,147,49,0.0,8,23.84,125.73,178,26.0,4.0,899.0,376,318,59.42,43.16,6.12
4,Melbourne Stars,1330,428,133,42,175,60,3.0,10,22.17,126.07,211,38.0,2.0,1015.0,532,252,58.95,42.17,5.80
5,Perth Scorchers,1492,482,117,61,178,60,2.0,11,24.87,123.61,211,58.0,3.0,1146.0,468,366,55.90,42.06,6.44
6,Sydney Sixers,1510,459,139,38,177,69,1.0,11,21.88,122.86,201,33.0,4.0,1192.0,556,228,51.92,38.51,6.73
7,Sydney Thunder,1318,413,106,43,149,74,3.0,9,17.81,120.70,200,29.0,5.0,1058.0,424,258,51.75,39.04,7.10

In [ ]:
batting_team_df['BpD'] = (batting_team_df['B']/batting_team_df['OUTS']).round(2)

In [ ]:
batting_team_df['strike Rotation%'] = (((batting_team_df['R'] - (batting_team_df['4Runs'] + batting_team_df['6Runs'])) / batting_team_df['R'])*100).round(2)

In [ ]:
batting_team_df['Rotation SR'] = (((batting_team_df['R'] - (batting_team_df['4Runs'] + batting_team_df['6Runs'])) / (batting_team_df['B'] - batting_team_df['DOTS'] - batting_team_df['BOUNDARY']))*100).round(2)

In [ ]:
batting_team_df

,batting_team,R,DOTS,4s,6s,BOUNDARY,OUTS,10W,I,AVG,...,noballs,B,4Runs,6Runs,Boundary %,Dot%,BpB,BpD,strike Rotation%,Rotation SR
0,Adelaide Strikers,1791,449,156,77,233,56,2.0,11,31.98,...,1.0,1227.0,624,462,60.64,36.59,5.27,21.91,39.36,129.36
1,Brisbane Heat,1655,498,141,59,200,76,3.0,11,21.78,...,3.0,1247.0,564,354,55.47,39.94,6.24,16.41,44.53,134.24
2,Hobart Hurricanes,1513,499,135,64,199,67,1.0,10,22.58,...,4.0,1147.0,540,384,61.07,43.50,5.76,17.12,38.93,131.18
3,Melbourne Renegades,1168,388,94,53,147,49,0.0,8,23.84,...,4.0,899.0,376,318,59.42,43.16,6.12,18.35,40.58,130.22
4,Melbourne Stars,1330,428,133,42,175,60,3.0,10,22.17,...,2.0,1015.0,532,252,58.95,42.17,5.80,16.92,41.05,132.52
5,Perth Scorchers,1492,482,117,61,178,60,2.0,11,24.87,...,3.0,1146.0,468,366,55.90,42.06,6.44,19.10,44.10,135.39
6,Sydney Sixers,1510,459,139,38,177,69,1.0,11,21.88,...,4.0,1192.0,556,228,51.92,38.51,6.73,17.28,48.08,130.58
7,Sydney Thunder,1318,413,106,43,149,74,3.0,9,17.81,...,5.0,1058.0,424,258,51.75,39.04,7.10,14.30,48.25,128.23

In [ ]:
batting_team_df.drop(columns=['BOUNDARY','wides','noballs','4Runs','6Runs','10W'],inplace=True)

In [ ]:
batting_team_df = batting_team_df[['batting_team','I','R','B','SR','AVG','DOTS','OUTS','HS','4s','6s','Boundary %','Dot%','BpB','BpD','strike Rotation%','Rotation SR']]

In [ ]:
batting_team_df

,batting_team,I,R,B,SR,AVG,DOTS,OUTS,HS,4s,6s,Boundary %,Dot%,BpB,BpD,strike Rotation%,Rotation SR
0,Adelaide Strikers,11,1791,1227.0,140.91,31.98,449,56,205,156,77,60.64,36.59,5.27,21.91,39.36,129.36
1,Brisbane Heat,11,1655,1247.0,127.41,21.78,498,76,214,141,59,55.47,39.94,6.24,16.41,44.53,134.24
2,Hobart Hurricanes,10,1513,1147.0,126.61,22.58,499,67,187,135,64,61.07,43.50,5.76,17.12,38.93,131.18
3,Melbourne Renegades,8,1168,899.0,125.73,23.84,388,49,178,94,53,59.42,43.16,6.12,18.35,40.58,130.22
4,Melbourne Stars,10,1330,1015.0,126.07,22.17,428,60,211,133,42,58.95,42.17,5.80,16.92,41.05,132.52
5,Perth Scorchers,11,1492,1146.0,123.61,24.87,482,60,211,117,61,55.90,42.06,6.44,19.10,44.10,135.39
6,Sydney Sixers,11,1510,1192.0,122.86,21.88,459,69,201,139,38,51.92,38.51,6.73,17.28,48.08,130.58
7,Sydney Thunder,9,1318,1058.0,120.70,17.81,413,74,200,106,43,51.75,39.04,7.10,14.30,48.25,128.23

In [ ]:
batting_team_df.to_excel('Master data index.xlsx',index=False)

In [ ]:
bowling_team_df = data.groupby('bowling_team')['runs_off_bat'].sum().reset_index()
bowling_team_df

          bowling_team  runs_off_bat
0    Adelaide Strikers          1838
1        Brisbane Heat          1485
2    Hobart Hurricanes          1417
3  Melbourne Renegades          1225
4      Melbourne Stars          1504
5      Perth Scorchers          1502
6        Sydney Sixers          1575
7       Sydney Thunder          1231

In [ ]:
ball_df = data.groupby('bowling_team')['ball'].count().reset_index()
ball_df

          bowling_team  ball
0    Adelaide Strikers  1321
1        Brisbane Heat  1286
2    Hobart Hurricanes  1108
3  Melbourne Renegades   952
4      Melbourne Stars  1126
5      Perth Scorchers  1199
6        Sydney Sixers  1301
7       Sydney Thunder   984

In [ ]:
bowling_team_df  = bowling_team_df.merge(ball_df,on='bowling_team',how='inner')

In [ ]:
bowling_team_df

          bowling_team  runs_off_bat  ball
0    Adelaide Strikers          1838  1321
1        Brisbane Heat          1485  1286
2    Hobart Hurricanes          1417  1108
3  Melbourne Renegades          1225   952
4      Melbourne Stars          1504  1126
5      Perth Scorchers          1502  1199
6        Sydney Sixers          1575  1301
7       Sydney Thunder          1231   984

In [ ]:
dots_df = data.groupby('bowling_team')['runs_off_bat'].apply(lambda x: (x==0).sum()).reset_index()

In [ ]:
dots_df

          bowling_team  runs_off_bat
0    Adelaide Strikers           474
1        Brisbane Heat           542
2    Hobart Hurricanes           412
3  Melbourne Renegades           383
4      Melbourne Stars           409
5      Perth Scorchers           504
6        Sydney Sixers           521
7       Sydney Thunder           371

In [ ]:
bowling_team_df = bowling_team_df.merge(dots_df,on='bowling_team',how='inner')

In [ ]:
bowling_team_df.rename(columns={'runs_off_bat_x':'R','ball':'B','runs_off_bat_y':'DOTS'},inplace=True)

In [ ]:
bowling_team_df

          bowling_team     R     B  DOTS
0    Adelaide Strikers  1838  1321   474
1        Brisbane Heat  1485  1286   542
2    Hobart Hurricanes  1417  1108   412
3  Melbourne Renegades  1225   952   383
4      Melbourne Stars  1504  1126   409
5      Perth Scorchers  1502  1199   504
6        Sydney Sixers  1575  1301   521
7       Sydney Thunder  1231   984   371

In [ ]:
wickets_count_df = data.groupby(['bowling_team'])['wicket_type'].count().reset_index()

In [ ]:
wickets_count_df.head(50)

          bowling_team  wicket_type
0    Adelaide Strikers           74
1        Brisbane Heat           97
2    Hobart Hurricanes           43
3  Melbourne Renegades           46
4      Melbourne Stars           55
5      Perth Scorchers           75
6        Sydney Sixers           75
7       Sydney Thunder           46

In [ ]:
bowling_team_df = bowling_team_df.merge(wickets_count_df,on='bowling_team',how='left')
bowling_team_df

          bowling_team     R     B  DOTS  wicket_type
0    Adelaide Strikers  1838  1321   474           74
1        Brisbane Heat  1485  1286   542           97
2    Hobart Hurricanes  1417  1108   412           43
3  Melbourne Renegades  1225   952   383           46
4      Melbourne Stars  1504  1126   409           55
5      Perth Scorchers  1502  1199   504           75
6        Sydney Sixers  1575  1301   521           75
7       Sydney Thunder  1231   984   371           46

In [ ]:
wickets_df = data.groupby(['bowling_team','match_id'])['wicket_type'].count().reset_index()

In [ ]:
result1 = pd.DataFrame({'bowling_team':all_teams})
# Perform a left join with all_teams to include all teams
all1 =  wickets_df[wickets_df['wicket_type'] == 10].groupby('bowling_team').size().reset_index()
all1.columns = ['bowling_team','10W']
result1 = result1.merge(all1,on='bowling_team',how='left').fillna(0)

In [ ]:
result1

          bowling_team  10W
0        Brisbane Heat  4.0
1      Melbourne Stars  1.0
2        Sydney Sixers  2.0
3  Melbourne Renegades  1.0
4      Perth Scorchers  3.0
5    Hobart Hurricanes  0.0
6       Sydney Thunder  2.0
7    Adelaide Strikers  2.0

In [ ]:
bowling_team_df = bowling_team_df.merge(result1,on='bowling_team',how='left')

In [ ]:
bowling_team_df

          bowling_team     R     B  DOTS  wicket_type  10W
0    Adelaide Strikers  1838  1321   474           74  2.0
1        Brisbane Heat  1485  1286   542           97  4.0
2    Hobart Hurricanes  1417  1108   412           43  0.0
3  Melbourne Renegades  1225   952   383           46  1.0
4      Melbourne Stars  1504  1126   409           55  1.0
5      Perth Scorchers  1502  1199   504           75  3.0
6        Sydney Sixers  1575  1301   521           75  2.0
7       Sydney Thunder  1231   984   371           46  2.0

In [ ]:
four_count_df = data.groupby('bowling_team')['runs_off_bat'].apply(lambda x: ((x==4).sum())).reset_index()
six_count_df = data.groupby('bowling_team')['runs_off_bat'].apply(lambda x:((x==6).sum())).reset_index()

In [ ]:
four_six_count_df = pd.merge(four_count_df,six_count_df,on='bowling_team',how='left')

In [ ]:
four_six_count_df.rename(columns={'runs_off_bat_x':'4s','runs_off_bat_y':'6s'},inplace=True)

In [ ]:
bowling_team_df = bowling_team_df.merge(four_six_count_df,on='bowling_team',how='left')

In [ ]:
bowling_team_df

          bowling_team     R     B  DOTS  wicket_type  10W   4s  6s
0    Adelaide Strikers  1838  1321   474           74  2.0  146  80
1        Brisbane Heat  1485  1286   542           97  4.0  114  56
2    Hobart Hurricanes  1417  1108   412           43  0.0  121  48
3  Melbourne Renegades  1225   952   383           46  1.0  109  51
4      Melbourne Stars  1504  1126   409           55  1.0  140  54
5      Perth Scorchers  1502  1199   504           75  3.0  144  54
6        Sydney Sixers  1575  1301   521           75  2.0  145  51
7       Sydney Thunder  1231   984   371           46  2.0  102  43

In [ ]:
bowling_team_df['ECO'] = ((bowling_team_df['R']/bowling_team_df['B']) * 6).round(2)

In [ ]:
bowling_team_df['AVG'] = (bowling_team_df['R']/bowling_team_df['wicket_type']).round(2)

In [ ]:
bowling_team_df['SR'] = ((bowling_team_df['R']/bowling_team_df['B'] * 100)).round(2)

In [ ]:
bowling_team_df.rename(columns={'wicket_type':'W'},inplace=True)

In [ ]:
bowling_team_df

,bowling_team,R,B,DOTS,W,10W,4s,6s,ECO,AVG,SR
0,Adelaide Strikers,1838,1321,474,74,2.0,146,80,8.35,24.84,139.14
1,Brisbane Heat,1485,1286,542,97,4.0,114,56,6.93,15.31,115.47
2,Hobart Hurricanes,1417,1108,412,43,0.0,121,48,7.67,32.95,127.89
3,Melbourne Renegades,1225,952,383,46,1.0,109,51,7.72,26.63,128.68
4,Melbourne Stars,1504,1126,409,55,1.0,140,54,8.01,27.35,133.57
5,Perth Scorchers,1502,1199,504,75,3.0,144,54,7.52,20.03,125.27
6,Sydney Sixers,1575,1301,521,75,2.0,145,51,7.26,21.00,121.06
7,Sydney Thunder,1231,984,371,46,2.0,102,43,7.51,26.76,125.10

In [ ]:
innings_count_df = data.groupby('bowling_team')['match_id'].nunique().reset_index(name='I')

In [ ]:
innings_count_df

          bowling_team   I
0    Adelaide Strikers  11
1        Brisbane Heat  11
2    Hobart Hurricanes  10
3  Melbourne Renegades   9
4      Melbourne Stars  10
5      Perth Scorchers  10
6        Sydney Sixers  11
7       Sydney Thunder   9

In [ ]:
bowling_team_df = bowling_team_df.merge(innings_count_df,on='bowling_team',how='left')

In [ ]:
#bowling_team_df.rename(columns={'bowling_team':'TEAMS'},inplace=True)

In [ ]:
bowling_team_df = bowling_team_df[['bowling_team','I','R','B','W','ECO','AVG','SR','10W','4s','6s','DOTS']]

In [ ]:
bowling_team_df

,bowling_team,I,R,B,W,ECO,AVG,SR,10W,4s,6s,DOTS
0,Adelaide Strikers,11,1838,1321,74,8.35,24.84,139.14,2.0,146,80,474
1,Brisbane Heat,11,1485,1286,97,6.93,15.31,115.47,4.0,114,56,542
2,Hobart Hurricanes,10,1417,1108,43,7.67,32.95,127.89,0.0,121,48,412
3,Melbourne Renegades,9,1225,952,46,7.72,26.63,128.68,1.0,109,51,383
4,Melbourne Stars,10,1504,1126,55,8.01,27.35,133.57,1.0,140,54,409
5,Perth Scorchers,10,1502,1199,75,7.52,20.03,125.27,3.0,144,54,504
6,Sydney Sixers,11,1575,1301,75,7.26,21.00,121.06,2.0,145,51,521
7,Sydney Thunder,9,1231,984,46,7.51,26.76,125.10,2.0,102,43,371

In [ ]:
extra_bowled = data.groupby(['bowling_team'])['wides','noballs'].sum().reset_index()

<ipython-input-136-f63bbf36ad14>:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  extra_bowled = data.groupby(['bowling_team'])['wides','noballs'].sum().reset_index()

In [ ]:
extra_bowled

          bowling_team  wides  noballs
0    Adelaide Strikers   39.0      2.0
1        Brisbane Heat   40.0      3.0
2    Hobart Hurricanes   54.0      5.0
3  Melbourne Renegades   34.0      1.0
4      Melbourne Stars   42.0      6.0
5      Perth Scorchers   29.0      3.0
6        Sydney Sixers   27.0      5.0
7       Sydney Thunder   55.0      1.0

In [ ]:
bowling_team_df = bowling_team_df.merge(extra_bowled,on='bowling_team',how='inner')

In [ ]:
bowling_team_df

,bowling_team,I,R,B,W,ECO,AVG,SR,10W,4s,6s,DOTS,wides,noballs
0,Adelaide Strikers,11,1838,1321,74,8.35,24.84,139.14,2.0,146,80,474,39.0,2.0
1,Brisbane Heat,11,1485,1286,97,6.93,15.31,115.47,4.0,114,56,542,40.0,3.0
2,Hobart Hurricanes,10,1417,1108,43,7.67,32.95,127.89,0.0,121,48,412,54.0,5.0
3,Melbourne Renegades,9,1225,952,46,7.72,26.63,128.68,1.0,109,51,383,34.0,1.0
4,Melbourne Stars,10,1504,1126,55,8.01,27.35,133.57,1.0,140,54,409,42.0,6.0
5,Perth Scorchers,10,1502,1199,75,7.52,20.03,125.27,3.0,144,54,504,29.0,3.0
6,Sydney Sixers,11,1575,1301,75,7.26,21.00,121.06,2.0,145,51,521,27.0,5.0
7,Sydney Thunder,9,1231,984,46,7.51,26.76,125.10,2.0,102,43,371,55.0,1.0

In [ ]:
bowling_team_df['CB'] = bowling_team_df['B'] - (bowling_team_df['wides'] + bowling_team_df['noballs'])

In [ ]:
bowling_team_df

,bowling_team,I,R,B,W,ECO,AVG,SR,10W,4s,6s,DOTS,wides,noballs,CB
0,Adelaide Strikers,11,1838,1321,74,8.35,24.84,139.14,2.0,146,80,474,39.0,2.0,1280.0
1,Brisbane Heat,11,1485,1286,97,6.93,15.31,115.47,4.0,114,56,542,40.0,3.0,1243.0
2,Hobart Hurricanes,10,1417,1108,43,7.67,32.95,127.89,0.0,121,48,412,54.0,5.0,1049.0
3,Melbourne Renegades,9,1225,952,46,7.72,26.63,128.68,1.0,109,51,383,34.0,1.0,917.0
4,Melbourne Stars,10,1504,1126,55,8.01,27.35,133.57,1.0,140,54,409,42.0,6.0,1078.0
5,Perth Scorchers,10,1502,1199,75,7.52,20.03,125.27,3.0,144,54,504,29.0,3.0,1167.0
6,Sydney Sixers,11,1575,1301,75,7.26,21.00,121.06,2.0,145,51,521,27.0,5.0,1269.0
7,Sydney Thunder,9,1231,984,46,7.51,26.76,125.10,2.0,102,43,371,55.0,1.0,928.0

In [ ]:
bowling_team_df.drop(columns=['B','wides','noballs'],inplace=True)

In [ ]:
bowling_team_df

,bowling_team,I,R,W,ECO,AVG,SR,10W,4s,6s,DOTS,CB
0,Adelaide Strikers,11,1838,74,8.35,24.84,139.14,2.0,146,80,474,1280.0
1,Brisbane Heat,11,1485,97,6.93,15.31,115.47,4.0,114,56,542,1243.0
2,Hobart Hurricanes,10,1417,43,7.67,32.95,127.89,0.0,121,48,412,1049.0
3,Melbourne Renegades,9,1225,46,7.72,26.63,128.68,1.0,109,51,383,917.0
4,Melbourne Stars,10,1504,55,8.01,27.35,133.57,1.0,140,54,409,1078.0
5,Perth Scorchers,10,1502,75,7.52,20.03,125.27,3.0,144,54,504,1167.0
6,Sydney Sixers,11,1575,75,7.26,21.00,121.06,2.0,145,51,521,1269.0
7,Sydney Thunder,9,1231,46,7.51,26.76,125.10,2.0,102,43,371,928.0

In [ ]:
bowling_team_df.rename(columns={'CB':'B'},inplace=True)

In [ ]:
bowling_team_df

,bowling_team,I,R,W,ECO,AVG,SR,10W,4s,6s,DOTS,B
0,Adelaide Strikers,11,1838,74,8.35,24.84,139.14,2.0,146,80,474,1280.0
1,Brisbane Heat,11,1485,97,6.93,15.31,115.47,4.0,114,56,542,1243.0
2,Hobart Hurricanes,10,1417,43,7.67,32.95,127.89,0.0,121,48,412,1049.0
3,Melbourne Renegades,9,1225,46,7.72,26.63,128.68,1.0,109,51,383,917.0
4,Melbourne Stars,10,1504,55,8.01,27.35,133.57,1.0,140,54,409,1078.0
5,Perth Scorchers,10,1502,75,7.52,20.03,125.27,3.0,144,54,504,1167.0
6,Sydney Sixers,11,1575,75,7.26,21.00,121.06,2.0,145,51,521,1269.0
7,Sydney Thunder,9,1231,46,7.51,26.76,125.10,2.0,102,43,371,928.0

In [ ]:
bowling_team_df['Boundary'] = bowling_team_df['4s'] + bowling_team_df['6s']

In [ ]:
bowling_team_df['4Runs'] = (bowling_team_df['4s']*4)

In [ ]:
bowling_team_df['6Runs'] = (bowling_team_df['6s']*6)

In [ ]:
bowling_team_df

,bowling_team,I,R,W,ECO,AVG,SR,10W,4s,6s,DOTS,B,Boundary,4Runs,6Runs
0,Adelaide Strikers,11,1838,74,8.35,24.84,139.14,2.0,146,80,474,1280.0,226,584,480
1,Brisbane Heat,11,1485,97,6.93,15.31,115.47,4.0,114,56,542,1243.0,170,456,336
2,Hobart Hurricanes,10,1417,43,7.67,32.95,127.89,0.0,121,48,412,1049.0,169,484,288
3,Melbourne Renegades,9,1225,46,7.72,26.63,128.68,1.0,109,51,383,917.0,160,436,306
4,Melbourne Stars,10,1504,55,8.01,27.35,133.57,1.0,140,54,409,1078.0,194,560,324
5,Perth Scorchers,10,1502,75,7.52,20.03,125.27,3.0,144,54,504,1167.0,198,576,324
6,Sydney Sixers,11,1575,75,7.26,21.00,121.06,2.0,145,51,521,1269.0,196,580,306
7,Sydney Thunder,9,1231,46,7.51,26.76,125.10,2.0,102,43,371,928.0,145,408,258

In [ ]:
bowling_team_df['Boundary %'] = (((bowling_team_df['4Runs'] + bowling_team_df['6Runs'])/bowling_team_df['R'])*100).round(2)

In [ ]:
bowling_team_df['Dot%'] = ((bowling_team_df['DOTS']/bowling_team_df['B'])*100).round(2)

In [ ]:
bowling_team_df['BpB'] = (bowling_team_df['B']/(bowling_team_df['4s']+bowling_team_df['6s'])).round(2)

In [ ]:
bowling_team_df['BpD'] = (bowling_team_df['B']/bowling_team_df['W']).round(2)

In [ ]:
bowling_team_df['strike Rotation%'] = (((bowling_team_df['R'] - (bowling_team_df['4Runs'] + bowling_team_df['6Runs'])) / bowling_team_df['R'])*100).round(2)

In [ ]:
bowling_team_df['Rotation SR'] = (((bowling_team_df['R'] - (bowling_team_df['4Runs'] + bowling_team_df['6Runs'])) / (bowling_team_df['B'] - bowling_team_df['DOTS']-bowling_team_df['Boundary']))*100).round(2)

In [ ]:
bowling_team_df

,bowling_team,I,R,W,ECO,AVG,SR,10W,4s,6s,...,B,Boundary,4Runs,6Runs,Boundary %,Dot%,BpB,BpD,strike Rotation%,Rotation SR
0,Adelaide Strikers,11,1838,74,8.35,24.84,139.14,2.0,146,80,...,1280.0,226,584,480,57.89,37.03,5.66,17.30,42.11,133.45
1,Brisbane Heat,11,1485,97,6.93,15.31,115.47,4.0,114,56,...,1243.0,170,456,336,53.33,43.60,7.31,12.81,46.67,130.51
2,Hobart Hurricanes,10,1417,43,7.67,32.95,127.89,0.0,121,48,...,1049.0,169,484,288,54.48,39.28,6.21,24.40,45.52,137.82
3,Melbourne Renegades,9,1225,46,7.72,26.63,128.68,1.0,109,51,...,917.0,160,436,306,60.57,41.77,5.73,19.93,39.43,129.14
4,Melbourne Stars,10,1504,55,8.01,27.35,133.57,1.0,140,54,...,1078.0,194,560,324,58.78,37.94,5.56,19.60,41.22,130.53
5,Perth Scorchers,10,1502,75,7.52,20.03,125.27,3.0,144,54,...,1167.0,198,576,324,59.92,43.19,5.89,15.56,40.08,129.46
6,Sydney Sixers,11,1575,75,7.26,21.00,121.06,2.0,145,51,...,1269.0,196,580,306,56.25,41.06,6.47,16.92,43.75,124.82
7,Sydney Thunder,9,1231,46,7.51,26.76,125.10,2.0,102,43,...,928.0,145,408,258,54.10,39.98,6.40,20.17,45.90,137.14

In [ ]:
bowling_team_df.drop(columns=['4Runs','6Runs','Boundary'],inplace=True)

In [ ]:
bowling_team_df = bowling_team_df[['bowling_team','I','R','B','DOTS','SR','AVG','W','ECO','4s','6s','Boundary %','Dot%','BpB','BpD','strike Rotation%','Rotation SR']]

In [ ]:
bowling_team_df

,bowling_team,I,R,B,DOTS,SR,AVG,W,ECO,4s,6s,Boundary %,Dot%,BpB,BpD,strike Rotation%,Rotation SR
0,Adelaide Strikers,11,1838,1280.0,474,139.14,24.84,74,8.35,146,80,57.89,37.03,5.66,17.30,42.11,133.45
1,Brisbane Heat,11,1485,1243.0,542,115.47,15.31,97,6.93,114,56,53.33,43.60,7.31,12.81,46.67,130.51
2,Hobart Hurricanes,10,1417,1049.0,412,127.89,32.95,43,7.67,121,48,54.48,39.28,6.21,24.40,45.52,137.82
3,Melbourne Renegades,9,1225,917.0,383,128.68,26.63,46,7.72,109,51,60.57,41.77,5.73,19.93,39.43,129.14
4,Melbourne Stars,10,1504,1078.0,409,133.57,27.35,55,8.01,140,54,58.78,37.94,5.56,19.60,41.22,130.53
5,Perth Scorchers,10,1502,1167.0,504,125.27,20.03,75,7.52,144,54,59.92,43.19,5.89,15.56,40.08,129.46
6,Sydney Sixers,11,1575,1269.0,521,121.06,21.00,75,7.26,145,51,56.25,41.06,6.47,16.92,43.75,124.82
7,Sydney Thunder,9,1231,928.0,371,125.10,26.76,46,7.51,102,43,54.10,39.98,6.40,20.17,45.90,137.14

In [ ]:
bowling_team_df.to_excel('Master data index 2.xlsx',index=False)